@CHARSET "ISO-8859-1";
.headerPanel {color:blue;font-size:16pt; margin-top:50px; width:600px;border:1px solid grey;}
.commandButton {color:black;font-size:12pt;}
.commandPanel, .componentPanel {color:blue;width:600px;border:5px solid grey;}
.pageOutputPanel {display:block;color:blue;width:600px;font-size:12pt;border:5px solid grey;}
.componentOutputPanel {color:red;font-size:12pt; border: 1pt solid black; width: 250px;border:5px solid orange;}